# Generated by Django 3.0.3 on 2020-02-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('emp_code', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Position')),
            ],
        ),
    ]
